/* The following code was generated by JFlex 1.4.3 on 12/3/15 10:54 AM */

import java.io.*;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/3/15 10:54 AM from the specification file
 * <tt>simpleC.flex</tt>
 */
public class Scanner implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\61\1\13"+
    "\2\0\1\53\1\62\1\0\1\42\1\43\1\12\1\57\1\51\1\60"+
    "\1\52\1\11\1\6\11\5\1\0\1\50\1\54\1\55\1\56\2\0"+
    "\13\4\1\66\1\4\1\64\6\4\1\65\5\4\1\46\1\0\1\47"+
    "\1\0\1\4\1\0\1\30\1\31\1\10\1\24\1\20\1\25\1\35"+
    "\1\33\1\14\1\4\1\32\1\26\1\34\1\15\1\23\1\41\1\4"+
    "\1\17\1\27\1\16\1\21\1\22\1\37\1\7\1\40\1\36\1\44"+
    "\1\63\1\45\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\4\1\3\1\5\1\6"+
    "\1\1\16\3\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\1\1\3\1\4\1\30\3\3"+
    "\1\0\1\31\1\32\1\0\1\33\1\3\1\34\10\3"+
    "\1\35\13\3\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\4\3\1\0\1\51"+
    "\14\3\1\52\17\3\1\53\1\54\1\55\4\3\1\56"+
    "\1\57\2\3\1\60\4\3\1\61\6\3\1\62\1\3"+
    "\1\63\1\3\1\64\1\3\1\65\4\3\1\66\4\3"+
    "\1\67\4\3\1\70\1\3\1\71\1\72\2\3\1\73"+
    "\1\3\1\74\3\3\1\75\1\76\1\77\1\100\1\101"+
    "\1\102\1\3\1\103\3\3\1\104\1\105\1\106\1\107"+
    "\1\110";

  private static int [] zzUnpackAction() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\67\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604"+
    "\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc"+
    "\0\u07f3\0\u082a\0\67\0\67\0\u01ef\0\67\0\u0861\0\245"+
    "\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19"+
    "\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\u0ce4"+
    "\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\245\0\u0df7\0\u0e2e\0\u0e65"+
    "\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d"+
    "\0\u1054\0\245\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e"+
    "\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356"+
    "\0\u138d\0\245\0\245\0\67\0\u13c4\0\u13fb\0\u1432\0\u1469"+
    "\0\245\0\245\0\u14a0\0\u14d7\0\245\0\u150e\0\u1545\0\u157c"+
    "\0\u15b3\0\245\0\u15ea\0\u1621\0\u1658\0\u168f\0\u16c6\0\u16fd"+
    "\0\245\0\u1734\0\245\0\u176b\0\245\0\u17a2\0\245\0\u17d9"+
    "\0\u1810\0\u1847\0\u187e\0\245\0\u18b5\0\u18ec\0\u1923\0\u195a"+
    "\0\245\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\245\0\u1a6d\0\245"+
    "\0\245\0\u1aa4\0\u1adb\0\245\0\u1b12\0\245\0\u1b49\0\u1b80"+
    "\0\u1bb7\0\245\0\245\0\245\0\245\0\245\0\245\0\u1bee"+
    "\0\245\0\u1c25\0\u1c5c\0\u1c93\0\245\0\245\0\245\0\245"+
    "\0\245";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\5\1\10"+
    "\1\11\1\12\1\13\1\14\1\5\1\15\1\16\1\17"+
    "\1\20\1\21\1\5\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\3\5\1\30\1\5\1\31\2\5\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\2\5\71\0\1\4\70\0\5\5\3\0\26\5"+
    "\22\0\3\5\5\0\2\55\1\56\66\0\1\56\63\0"+
    "\5\5\3\0\7\5\1\57\4\5\1\60\2\5\1\61"+
    "\6\5\22\0\3\5\12\0\1\62\42\0\1\63\66\0"+
    "\1\64\11\0\13\65\1\66\53\65\4\0\5\5\3\0"+
    "\1\5\1\67\7\5\1\70\14\5\22\0\3\5\4\0"+
    "\5\5\3\0\24\5\1\71\1\5\22\0\3\5\4\0"+
    "\5\5\3\0\4\5\1\72\21\5\22\0\3\5\4\0"+
    "\3\5\1\73\1\5\3\0\1\5\1\74\10\5\1\75"+
    "\13\5\22\0\3\5\4\0\5\5\3\0\1\5\1\76"+
    "\24\5\22\0\3\5\4\0\5\5\3\0\7\5\1\77"+
    "\16\5\22\0\3\5\4\0\5\5\3\0\4\5\1\100"+
    "\2\5\1\101\16\5\22\0\3\5\4\0\5\5\3\0"+
    "\7\5\1\102\2\5\1\103\13\5\22\0\3\5\4\0"+
    "\5\5\3\0\7\5\1\104\16\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\105\1\5\1\106\14\5\1\107\3\5"+
    "\1\110\2\5\22\0\3\5\4\0\5\5\3\0\5\5"+
    "\1\111\20\5\22\0\3\5\4\0\5\5\3\0\3\5"+
    "\1\112\22\5\22\0\3\5\4\0\5\5\3\0\7\5"+
    "\1\113\16\5\22\0\3\5\4\0\5\5\3\0\17\5"+
    "\1\114\6\5\22\0\3\5\54\0\1\115\1\116\66\0"+
    "\1\117\66\0\1\120\1\121\65\0\1\122\66\0\1\123"+
    "\1\124\65\0\1\125\73\0\1\126\67\0\1\127\7\0"+
    "\5\5\3\0\26\5\22\0\1\5\1\130\1\5\5\0"+
    "\2\55\65\0\2\56\1\0\1\56\7\0\1\56\3\0"+
    "\2\56\2\0\2\56\41\0\5\5\3\0\1\5\1\131"+
    "\24\5\22\0\3\5\4\0\5\5\3\0\13\5\1\132"+
    "\12\5\22\0\3\5\4\0\5\5\3\0\14\5\1\133"+
    "\11\5\22\0\3\5\12\62\1\134\54\62\4\0\5\5"+
    "\3\0\2\5\1\135\23\5\22\0\3\5\4\0\5\5"+
    "\3\0\25\5\1\136\22\0\3\5\4\0\5\5\3\0"+
    "\2\5\1\137\16\5\1\140\4\5\22\0\3\5\4\0"+
    "\5\5\3\0\2\5\1\141\23\5\22\0\3\5\4\0"+
    "\5\5\3\0\5\5\1\142\20\5\22\0\3\5\4\0"+
    "\5\5\3\0\13\5\1\143\12\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\144\12\5\1\145\12\5\22\0\3\5"+
    "\4\0\5\5\3\0\1\146\11\5\1\147\13\5\22\0"+
    "\3\5\4\0\5\5\3\0\11\5\1\150\14\5\22\0"+
    "\3\5\4\0\5\5\3\0\5\5\1\151\20\5\22\0"+
    "\3\5\4\0\5\5\3\0\3\5\1\152\22\5\22\0"+
    "\3\5\4\0\5\5\3\0\7\5\1\153\16\5\22\0"+
    "\3\5\4\0\5\5\3\0\1\5\1\154\24\5\22\0"+
    "\3\5\4\0\5\5\3\0\21\5\1\155\1\156\3\5"+
    "\22\0\3\5\4\0\5\5\3\0\3\5\1\157\10\5"+
    "\1\160\11\5\22\0\3\5\4\0\5\5\3\0\7\5"+
    "\1\161\16\5\22\0\3\5\4\0\5\5\3\0\1\162"+
    "\25\5\22\0\3\5\4\0\5\5\3\0\2\5\1\163"+
    "\23\5\22\0\3\5\4\0\5\5\3\0\4\5\1\164"+
    "\21\5\22\0\3\5\4\0\5\5\3\0\2\5\1\165"+
    "\23\5\22\0\3\5\4\0\5\5\3\0\1\166\25\5"+
    "\22\0\3\5\4\0\5\5\3\0\26\5\22\0\2\5"+
    "\1\167\4\0\5\5\3\0\2\5\1\170\10\5\1\171"+
    "\12\5\22\0\3\5\4\0\5\5\3\0\4\5\1\172"+
    "\21\5\22\0\3\5\4\0\5\5\3\0\3\5\1\173"+
    "\22\5\22\0\3\5\11\62\1\174\55\62\4\0\5\5"+
    "\3\0\4\5\1\175\21\5\22\0\3\5\4\0\5\5"+
    "\3\0\5\5\1\176\20\5\22\0\3\5\4\0\5\5"+
    "\3\0\1\177\25\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\200\21\5\22\0\3\5\4\0\5\5\3\0"+
    "\20\5\1\201\5\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\202\21\5\22\0\3\5\4\0\5\5\3\0"+
    "\7\5\1\203\16\5\22\0\3\5\4\0\5\5\3\0"+
    "\1\204\25\5\22\0\3\5\4\0\5\5\3\0\10\5"+
    "\1\205\15\5\22\0\3\5\4\0\5\5\3\0\14\5"+
    "\1\206\11\5\22\0\3\5\4\0\5\5\3\0\14\5"+
    "\1\207\11\5\22\0\3\5\4\0\5\5\3\0\15\5"+
    "\1\210\10\5\22\0\3\5\4\0\5\5\3\0\14\5"+
    "\1\211\11\5\22\0\3\5\4\0\5\5\3\0\21\5"+
    "\1\212\4\5\22\0\3\5\4\0\5\5\3\0\1\5"+
    "\1\213\24\5\22\0\3\5\4\0\5\5\3\0\4\5"+
    "\1\214\21\5\22\0\3\5\4\0\5\5\3\0\5\5"+
    "\1\215\20\5\22\0\3\5\4\0\5\5\3\0\2\5"+
    "\1\216\23\5\22\0\3\5\4\0\5\5\3\0\3\5"+
    "\1\217\22\5\22\0\3\5\4\0\5\5\3\0\2\5"+
    "\1\220\23\5\22\0\3\5\4\0\5\5\3\0\7\5"+
    "\1\221\16\5\22\0\3\5\4\0\5\5\3\0\14\5"+
    "\1\222\11\5\22\0\3\5\4\0\5\5\3\0\7\5"+
    "\1\223\16\5\22\0\3\5\4\0\5\5\3\0\12\5"+
    "\1\224\13\5\22\0\3\5\4\0\5\5\3\0\26\5"+
    "\22\0\2\5\1\225\4\0\5\5\3\0\1\226\25\5"+
    "\22\0\3\5\4\0\5\5\3\0\2\5\1\227\23\5"+
    "\22\0\3\5\4\0\5\5\3\0\10\5\1\230\15\5"+
    "\22\0\3\5\4\0\5\5\3\0\3\5\1\231\22\5"+
    "\22\0\3\5\4\0\5\5\3\0\13\5\1\232\12\5"+
    "\22\0\3\5\4\0\5\5\3\0\3\5\1\233\22\5"+
    "\22\0\3\5\4\0\5\5\3\0\1\5\1\234\24\5"+
    "\22\0\3\5\4\0\5\5\3\0\21\5\1\235\4\5"+
    "\22\0\3\5\4\0\5\5\3\0\2\5\1\236\23\5"+
    "\22\0\3\5\4\0\5\5\3\0\5\5\1\237\20\5"+
    "\22\0\3\5\4\0\5\5\3\0\12\5\1\240\13\5"+
    "\22\0\3\5\4\0\5\5\3\0\2\5\1\241\23\5"+
    "\22\0\3\5\4\0\5\5\3\0\4\5\1\242\21\5"+
    "\22\0\3\5\4\0\5\5\3\0\7\5\1\243\16\5"+
    "\22\0\3\5\4\0\4\5\1\244\3\0\26\5\22\0"+
    "\3\5\4\0\5\5\3\0\1\245\25\5\22\0\3\5"+
    "\4\0\5\5\3\0\2\5\1\246\23\5\22\0\3\5"+
    "\4\0\4\5\1\247\3\0\26\5\22\0\3\5\4\0"+
    "\5\5\3\0\16\5\1\250\7\5\22\0\3\5\4\0"+
    "\5\5\3\0\4\5\1\251\21\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\5\1\252\24\5\22\0\3\5\4\0"+
    "\5\5\3\0\4\5\1\253\21\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\5\1\254\24\5\22\0\3\5\4\0"+
    "\5\5\3\0\2\5\1\255\23\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\5\1\256\24\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\5\1\257\24\5\22\0\3\5\4\0"+
    "\5\5\3\0\1\260\25\5\22\0\3\5\4\0\5\5"+
    "\3\0\12\5\1\261\13\5\22\0\3\5\4\0\5\5"+
    "\3\0\4\5\1\262\21\5\22\0\3\5\4\0\5\5"+
    "\3\0\10\5\1\263\15\5\22\0\3\5\4\0\5\5"+
    "\3\0\11\5\1\264\14\5\22\0\3\5\4\0\5\5"+
    "\3\0\2\5\1\265\23\5\22\0\3\5\4\0\4\5"+
    "\1\266\3\0\26\5\22\0\3\5\4\0\5\5\3\0"+
    "\17\5\1\267\6\5\22\0\3\5\4\0\5\5\3\0"+
    "\5\5\1\270\20\5\22\0\3\5\4\0\5\5\3\0"+
    "\11\5\1\271\14\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\272\21\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\273\21\5\22\0\3\5\4\0\5\5\3\0"+
    "\12\5\1\274\13\5\22\0\3\5\4\0\5\5\3\0"+
    "\2\5\1\275\23\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\276\21\5\22\0\3\5\4\0\5\5\3\0"+
    "\3\5\1\277\22\5\22\0\3\5\4\0\5\5\3\0"+
    "\10\5\1\300\15\5\22\0\3\5\4\0\5\5\3\0"+
    "\4\5\1\301\21\5\22\0\3\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7370];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\25\1\12\11\16\1\1\0"+
    "\2\11\1\0\1\11\26\1\13\11\4\1\1\0\37\1"+
    "\1\11\105\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new MySymbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new MySymbol(type, yyline+1, yycolumn+1, value);
  } 


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return symbol(INTLITERAL, new Integer(yytext()));
          }
        case 73: break;
        case 54: 
          { return symbol(UNION);
          }
        case 74: break;
        case 62: 
          { return symbol(SIGNED);
          }
        case 75: break;
        case 69: 
          { return symbol(CONTINUE);
          }
        case 76: break;
        case 24: 
          { String s = yytext().substring(2);
	s = s.toUpperCase();
	Integer t = Integer.parseInt(s , 16);
	return symbol(HEXLITERAL, t);
          }
        case 77: break;
        case 29: 
          { return symbol(DO);
          }
        case 78: break;
        case 65: 
          { return symbol(STATIC);
          }
        case 79: break;
        case 72: 
          { return symbol(VOLATILE);
          }
        case 80: break;
        case 25: 
          { return symbol(DIVEQL);
          }
        case 81: break;
        case 19: 
          { return symbol(GREATER);
          }
        case 82: break;
        case 3: 
          { return symbol(ID, yytext());
          }
        case 83: break;
        case 6: 
          { return symbol(TIMES);
          }
        case 84: break;
        case 33: 
          { return symbol(GREATEREQ);
          }
        case 85: break;
        case 56: 
          { return symbol(SHORT);
          }
        case 86: break;
        case 11: 
          { return symbol(LSQBRACKET);
          }
        case 87: break;
        case 52: 
          { return symbol(NULL);
          }
        case 88: break;
        case 5: 
          { return symbol(DIVIDE);
          }
        case 89: break;
        case 15: 
          { return symbol(PERIOD);
          }
        case 90: break;
        case 49: 
          { return symbol(LONG);
          }
        case 91: break;
        case 40: 
          { return symbol(OR);
          }
        case 92: break;
        case 20: 
          { return symbol(PLUS);
          }
        case 93: break;
        case 1: 
          { Errors.fatal(yyline+1, yycolumn+1, "Illegal character \"" + yytext()+ "\""); 
       System.exit(-1);
          }
        case 94: break;
        case 8: 
          { return symbol(RPAREN);
          }
        case 95: break;
        case 53: 
          { return symbol(CONST);
          }
        case 96: break;
        case 50: 
          { return symbol(AUTO);
          }
        case 97: break;
        case 27: 
          { return symbol(STRINGLITERAL, yytext());
          }
        case 98: break;
        case 16: 
          { return symbol(PERCENT);
          }
        case 99: break;
        case 18: 
          { return symbol(ASSIGN);
          }
        case 100: break;
        case 46: 
          { return symbol(ENUM);
          }
        case 101: break;
        case 45: 
          { return symbol(COMMENT);
          }
        case 102: break;
        case 36: 
          { return symbol(MINUSEQL);
          }
        case 103: break;
        case 42: 
          { return symbol(FOR);
          }
        case 104: break;
        case 51: 
          { return symbol(GOTO);
          }
        case 105: break;
        case 23: 
          { return symbol(ADDROF);
          }
        case 106: break;
        case 32: 
          { return symbol(EQUALS);
          }
        case 107: break;
        case 26: 
          { return symbol(TIMESEQL);
          }
        case 108: break;
        case 68: 
          { return symbol(DEFAULT);
          }
        case 109: break;
        case 28: 
          { return symbol(IF);
          }
        case 110: break;
        case 44: 
          { return symbol(CHAR);
          }
        case 111: break;
        case 61: 
          { return symbol(DOUBLE);
          }
        case 112: break;
        case 66: 
          { return symbol(SWITCH);
          }
        case 113: break;
        case 7: 
          { return symbol(LPAREN);
          }
        case 114: break;
        case 57: 
          { return symbol(BREAK);
          }
        case 115: break;
        case 60: 
          { return symbol(EXTERN);
          }
        case 116: break;
        case 10: 
          { return symbol(RCURLY);
          }
        case 117: break;
        case 67: 
          { return symbol(TYPEDEF);
          }
        case 118: break;
        case 13: 
          { return symbol(SEMICOLON);
          }
        case 119: break;
        case 38: 
          { return symbol(NOTEQUALS);
          }
        case 120: break;
        case 55: 
          { return symbol(FLOAT);
          }
        case 121: break;
        case 30: 
          { return symbol(WRITE);
          }
        case 122: break;
        case 43: 
          { return symbol(CASE);
          }
        case 123: break;
        case 21: 
          { return symbol(MINUS);
          }
        case 124: break;
        case 12: 
          { return symbol(RSQBRACKET);
          }
        case 125: break;
        case 70: 
          { return symbol(REGISTER);
          }
        case 126: break;
        case 41: 
          { return symbol(INT);
          }
        case 127: break;
        case 39: 
          { return symbol(AND);
          }
        case 128: break;
        case 9: 
          { return symbol(LCURLY);
          }
        case 129: break;
        case 71: 
          { return symbol(UNSIGNED);
          }
        case 130: break;
        case 63: 
          { return symbol(SIZEOF);
          }
        case 131: break;
        case 48: 
          { return symbol(VOID);
          }
        case 132: break;
        case 22: 
          { return symbol(NOT);
          }
        case 133: break;
        case 2: 
          { /* ignore */
          }
        case 134: break;
        case 34: 
          { return symbol(READ);
          }
        case 135: break;
        case 64: 
          { return symbol(STRUCT);
          }
        case 136: break;
        case 37: 
          { return symbol(STRDEREF);
          }
        case 137: break;
        case 35: 
          { return symbol(PLUSEQL);
          }
        case 138: break;
        case 58: 
          { return symbol(WHILE);
          }
        case 139: break;
        case 17: 
          { return symbol(LESS);
          }
        case 140: break;
        case 47: 
          { return symbol(ELSE);
          }
        case 141: break;
        case 14: 
          { return symbol(COMMA);
          }
        case 142: break;
        case 31: 
          { return symbol(LESSEQ);
          }
        case 143: break;
        case 59: 
          { return symbol(RETURN);
          }
        case 144: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          scanner = new Scanner( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
