
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 30 18:37:01 ICT 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSEQL = 47;		// +=
  public static final int DIVIDE = 30;  	// /
  public static final int MINUSEQL = 48;	// -=
  public static final int EQUALS = 34;		// ==
  public static final int PERIOD = 44; 		// .
  public static final int DIVEQL = 50;		// /=
  public static final int GREATER = 37;		// >
  public static final int LPAREN = 22;		// (
  public static final int INT = 2;			// int
  public static final int LESS = 36;		// <
  public static final int FOR = 11;			// for
  public static final int MINUS = 28;		// -
  public static final int WRITE = 41;		// <<
  public static final int RPAREN = 23;		// )
  public static final int SIZEOF = 43;		// sizeof
  public static final int NOT = 31;			// !
  public static final int SEMICOLON = 26;	// ;
  public static final int AND = 32;			// &&
  public static final int OR = 33;			// ||
  public static final int COMMA = 24;		// ,
  public static final int PLUS = 27;		// +
  public static final int LESSEQ = 38;		// <=
  public static final int ASSIGN = 25;		// =
  public static final int IF = 8;			// if
  public static final int TIMESEQL = 49;	// *=
  public static final int ID = 15;			// identifier
  public static final int EOF = 0;			// end of file
  public static final int RETURN = 14;		// return 
  public static final int error = 1;		// error
  public static final int PERCENT = 51;		// %
  public static final int LCURLY = 18;		// {
  public static final int NULL = 7;			// NULL
  public static final int LSQBRACKET = 20;	// [
  public static final int VOID = 4;			// void
  public static final int RCURLY = 19;		// }
  public static final int INTLITERAL = 16;	// an integer number
  public static final int TIMES = 29;		// *
  public static final int ELSE = 9;			// else
  public static final int READ = 40;		// >>
  public static final int NOTEQUALS = 35;	// !=
  public static final int WHILE = 10;		// while
  public static final int ADDROF = 42;		// &
  public static final int RSQBRACKET = 21;	// ]
  public static final int GREATEREQ = 39;	// >=
  public static final int STRINGLITERAL = 17;// string literal
  public static final int STRUCT = 46;		// struct
  public static final int STRDEREF = 45;	// ->
  
  
  public static final int DO = 101;			// do
  public static final int DOUBLE = 102;		// while
  public static final int FLOAT = 103;		// float
  public static final int EXTERN = 104;		// extern
  public static final int PLUSPLUS = 105;	// ++
  public static final int READEQL = 106;	// >>=
  public static final int WRITEEQL = 107;	// <<=
  public static final int FLOATING_POINT_LITERAL = 108;	//	a floating-point number
  public static final int CONST = 109;		//	const
  public static final int COMMENT = 110;	// a comment
  
}

